//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 

namespace Framework.Logic.Email.WebServiceProxy
{
    using System.Configuration;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://www.nedbank.co.za/EmailService")]
    public partial class EmailServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;

        private System.Threading.SendOrPostCallback CheckMailStatusOperationCompleted;

        /// <remarks/>
        public EmailServiceProxy()
        {
            this.Url = ConfigurationManager.AppSettings["EmailWebService"];
        }

        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;

        /// <remarks/>
        public event CheckMailStatusCompletedEventHandler CheckMailStatusCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nedbank.co.za/EmailService/SendEmail", RequestNamespace = "http://www.nedbank.co.za/EmailService", ResponseNamespace = "http://www.nedbank.co.za/EmailService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SendEmail(EmailMessage message)
        {
            object[] results = this.Invoke("SendEmail", new object[] {
                    message});
            return ((long)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendEmail(EmailMessage message, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SendEmail", new object[] {
                    message}, callback, asyncState);
        }

        /// <remarks/>
        public long EndSendEmail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }

        /// <remarks/>
        public void SendEmailAsync(EmailMessage message)
        {
            this.SendEmailAsync(message, null);
        }

        /// <remarks/>
        public void SendEmailAsync(EmailMessage message, object userState)
        {
            if((this.SendEmailOperationCompleted == null))
            {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                    message}, this.SendEmailOperationCompleted, userState);
        }

        private void OnSendEmailOperationCompleted(object arg)
        {
            if((this.SendEmailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nedbank.co.za/EmailService/CheckMailStatus", RequestNamespace = "http://www.nedbank.co.za/EmailService", ResponseNamespace = "http://www.nedbank.co.za/EmailService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailResult CheckMailStatus(long messageID)
        {
            object[] results = this.Invoke("CheckMailStatus", new object[] {
                    messageID});
            return ((EmailResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCheckMailStatus(long messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CheckMailStatus", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public EmailResult EndCheckMailStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmailResult)(results[0]));
        }

        /// <remarks/>
        public void CheckMailStatusAsync(long messageID)
        {
            this.CheckMailStatusAsync(messageID, null);
        }

        /// <remarks/>
        public void CheckMailStatusAsync(long messageID, object userState)
        {
            if((this.CheckMailStatusOperationCompleted == null))
            {
                this.CheckMailStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMailStatusOperationCompleted);
            }
            this.InvokeAsync("CheckMailStatus", new object[] {
                    messageID}, this.CheckMailStatusOperationCompleted, userState);
        }

        private void OnCheckMailStatusOperationCompleted(object arg)
        {
            if((this.CheckMailStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMailStatusCompleted(this, new CheckMailStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService/Contracts")]
    public partial class EmailMessage
    {

        private string fromAddressField;

        private string[] toAddressField;

        private string[] cCAddressField;

        private string[] bCCAddressField;

        private string subjectField;

        private string bodyField;

        private Format bodyFormatField;

        private bool bodyFormatFieldSpecified;

        private DeliveryOptions notificationOptionsField;

        private bool notificationOptionsFieldSpecified;

        private string sendReceiptToField;

        private Priority mailPriorityField;

        private bool mailPriorityFieldSpecified;

        private string applicationField;

        private Attachment[] attachmentsField;

        /// <remarks/>
        public string FromAddress
        {
            get
            {
                return this.fromAddressField;
            }
            set
            {
                this.fromAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ToAddress")]
        public string[] ToAddress
        {
            get
            {
                return this.toAddressField;
            }
            set
            {
                this.toAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CCAddress")]
        public string[] CCAddress
        {
            get
            {
                return this.cCAddressField;
            }
            set
            {
                this.cCAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BCCAddress")]
        public string[] BCCAddress
        {
            get
            {
                return this.bCCAddressField;
            }
            set
            {
                this.bCCAddressField = value;
            }
        }

        /// <remarks/>
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        public Format BodyFormat
        {
            get
            {
                return this.bodyFormatField;
            }
            set
            {
                this.bodyFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BodyFormatSpecified
        {
            get
            {
                return this.bodyFormatFieldSpecified;
            }
            set
            {
                this.bodyFormatFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DeliveryOptions NotificationOptions
        {
            get
            {
                return this.notificationOptionsField;
            }
            set
            {
                this.notificationOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotificationOptionsSpecified
        {
            get
            {
                return this.notificationOptionsFieldSpecified;
            }
            set
            {
                this.notificationOptionsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string SendReceiptTo
        {
            get
            {
                return this.sendReceiptToField;
            }
            set
            {
                this.sendReceiptToField = value;
            }
        }

        /// <remarks/>
        public Priority MailPriority
        {
            get
            {
                return this.mailPriorityField;
            }
            set
            {
                this.mailPriorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MailPrioritySpecified
        {
            get
            {
                return this.mailPriorityFieldSpecified;
            }
            set
            {
                this.mailPriorityFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public Attachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService/Contracts")]
    public enum Format
    {

        /// <remarks/>
        Text,

        /// <remarks/>
        HTML,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService/Contracts")]
    public enum DeliveryOptions
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Delay,

        /// <remarks/>
        OnFailure,

        /// <remarks/>
        OnSuccess,

        /// <remarks/>
        All,

        /// <remarks/>
        OnFailureOrSuccess,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService/Contracts")]
    public enum Priority
    {

        /// <remarks/>
        Low,

        /// <remarks/>
        Medium,

        /// <remarks/>
        High,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService/Contracts")]
    public partial class Attachment
    {

        private string fileNameField;

        private byte[] bytesField;

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Bytes
        {
            get
            {
                return this.bytesField;
            }
            set
            {
                this.bytesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.nedbank.co.za/EmailService")]
    public partial class EmailResult
    {

        private bool handledField;

        private System.DateTime handledDateField;

        private bool succesfulField;

        private string erroMessageField;

        /// <remarks/>
        public bool Handled
        {
            get
            {
                return this.handledField;
            }
            set
            {
                this.handledField = value;
            }
        }

        /// <remarks/>
        public System.DateTime HandledDate
        {
            get
            {
                return this.handledDateField;
            }
            set
            {
                this.handledDateField = value;
            }
        }

        /// <remarks/>
        public bool Succesful
        {
            get
            {
                return this.succesfulField;
            }
            set
            {
                this.succesfulField = value;
            }
        }

        /// <remarks/>
        public string ErroMessage
        {
            get
            {
                return this.erroMessageField;
            }
            set
            {
                this.erroMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public long Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void CheckMailStatusCompletedEventHandler(object sender, CheckMailStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMailStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CheckMailStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public EmailResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((EmailResult)(this.results[0]));
            }
        }
    }
}